### ISSUE TITLE
`make test` depends on unittest-data-provider

### ISSUE THREAD

**Issue by thierry-FreeBSD** [Kosmorro/kosmorro#147]
`make test` depends on unittest-data-provider, which is deprecated:
on the page https://github.com/yourlabs/unittest-data-provider the title is now
**!!! Don't use this, try pytest parameterize instead !!! See this url: https://docs.pytest.org/en/latest/parametrize.html**

**Comment by Deuchnord** [comment]
Thanks for having reported this!
We should definitely remove this library if it is not recommended anymore by its author :)
