### ISSUE TITLE
Make a Docker image

### ISSUE THREAD

**Issue by Deuchnord** [Kosmorro/kosmorro#19]
Suggested by @Pierstoval [on Twitter](https://twitter.com/Pierstoval/status/1192406525383454720): create an official Docker image.

**Comment by nicfb** [comment]
Is this still something you're wanting for Kosmorro? I'd love to give it a try.

**Comment by Deuchnord** [comment]
> Is this still something you're wanting for Kosmorro? I'd love to give it a try.

Yes, it is! Making a Docker image would dramatically simplify the use of the program for the people who want to use it without necessarily install it :)

**Comment by nicfb** [comment]
I think I have something working. I'm planning on making a PR tomorrow so you can check it out.

**Comment by Deuchnord** [comment]
Since this can be added to the v0.9 to be released soon, you can base your PR to `master` directly :)

**Comment by nicfb** [comment]
Great! What should be included in the commit, just the Dockerfile? And will the image need to be hosted somewhere like [Docker Hub](https://hub.docker.com)? This is my first time working with Docker, so I'm not sure what should be checked into git.

**Comment by Deuchnord** [comment]
You may update the "installation" section of the Readme, to inform the users about the available image.

> And will the image need to be hosted somewhere like Docker Hub? This is my first time working with Docker, so I'm not sure what should be checked into git.

Yes, it will! The image will be named `kosmorro/kosmorro`. I think you can add [this GitHub Action workflow](https://github.com/marketplace/actions/build-and-push-docker-images), with execution on tag push :slightly_smiling_face:

**Comment by nicfb** [comment]
Ok. Sorry the late reply, I haven't had much time to dedicate to this in the past few days. I'm familiarizing myself with GitHub Actions right now, but I think I will have it ready soon.

**Comment by Deuchnord** [comment]
Don't worry, you have time for this 😉

**Comment by nicfb** [comment]
I have opened the PR. Please let me know if you see anything that I need to fix.
