### ISSUE TITLE
Add support for the NO_COLOR standard environment variable

### ISSUE THREAD

**Issue by Deuchnord** [Kosmorro/kosmorro#210]
**Is your feature request related to a problem? Please describe.**
If I don't want colors to be displayed on the return of the command, I currently need to add the `--no-color` argument. But if I want them to _never_ show up, then there is no other solution but always adding this argument.

**Describe the solution you'd like**
Add support for the [`NO_COLOR`](https://no-color.org/) standard: if an environment variable named `NO_COLOR` exists, disable the display of colors. The environment variable just have to exist, its value is not important.

**Comment by nicfb** [comment]
Hello! I think I have something working for this. Should I submit a PR? Or are you already working on this?

**Comment by Deuchnord** [comment]
I didn't start working on this, you can submit a PR :)

**Comment by Deuchnord** [comment]
Closing this issue, done in #220.
